"""empty message

Revision ID: 12c255fb027a
Revises: ebc7fac54ce1
Create Date: 2022-12-14 04:09:32.862007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c255fb027a'
down_revision = 'ebc7fac54ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fileupload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin', sa.LargeBinary(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fileupload')
    # ### end Alembic commands ###
