"""empty message

Revision ID: 308692c3e87f
Revises: 2afb1e2231cb
Create Date: 2022-12-11 18:53:15.916134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308692c3e87f'
down_revision = '2afb1e2231cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('new_text', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info')
    # ### end Alembic commands ###
