"""empty message

Revision ID: 5720711744ed
Revises: 12c255fb027a
Create Date: 2022-12-16 21:10:18.303991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5720711744ed'
down_revision = '12c255fb027a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fileupload')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fileupload',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bin', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='fileupload_pkey')
    )
    # ### end Alembic commands ###
