"""empty message

Revision ID: a5cfb70c6574
Revises: 308692c3e87f
Create Date: 2022-12-11 18:58:46.894661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5cfb70c6574'
down_revision = '308692c3e87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.alter_column('new_text',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.alter_column('new_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
